server:
  port: 7001

spring:
  application:
    name: eureka-client

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/ # eureka server registry url
