server:
  port: 8401

spring:
  application:
    name: resilience4j-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

custom-service-url:
  user-service: http://user-service

