server:
  port: 8201

spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411 # 指定 zipkin web 访问地址
  sleuth:
    sampler:
      probability: 0.1 # sleuth 的抽样收集概率

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
