server:
  port: 8206

spring:
  application:
    name: consul-user-service
  zipkin:
    base-url: http://localhost:9411 # 指定 zipkin web 访问地址
  sleuth:
    sampler:
      probability: 0.1 # sleuth 的抽样收集概率
  cloud:
    consul: # consul 服务注册发现配置
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
