server:
  port: 8002

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: replica1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8003/eureka/
