server:
  port: 8301

spring:
  application:
    name: loadbalancer-service
  zipkin:
    base-url: http://localhost:9411 # 指定 zipkin-server 的访问地址
  sleuth:
    sampler:
      probability: 0.1 # sleuth 的抽样收集概率


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

# 自定义配置
custom-service-url:
  # 服务提供地址，"user-service" 是服务提供模块中配置的应用名称
  # spring cloud 会根据应用名称从服务注册中心自动获取对应的服务地址，并自动实现负载均衡
  # 默认的负载均衡策略为轮询
  user-service: http://user-service

